/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "intro": {
    "Unoparty Intro": [
      "intro",
    ],
    "What is Unoparty?": [
      "what-is-unoparty/A-Unobtanium-Protocol",
      "what-is-unoparty/An-incencentivization-token",
    ],
    "Assets token/NFTS": [
      "assets/enhanced-asset",
      "assets/enhanced-feed",
      "assets/use-cases",
    ],
    "FAQ": [
      "faq/general",
    ]
  },
  "wallets": {
    "Unowallet": [
      "wallets/unowalletfaq",
      "wallets/unowallet-notes"
    ],
    "Unowallet Tutorial": [
      "wallets/tuts/getting-started",
    ]
  },
  "advanced": {
    "Architecture/Protocol": [
      "advanced/architecture",
      "advanced/protocol",
    ],
    "Command-Line": [
      "advanced/cli",
    ],
    "Advanced Usage": [
      "advanced/sending-bulk",
    ]
  },
  "Develop": {
    "Unoparty API" : [
      "develop/api/overview",
      "develop/api",
    ],
    "Unoblock": [
      "develop/unoblock/api"
    ],
  }
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['assets'],
    },
  ],
*/
};

module.exports = sidebars;
